import { randomBytes } from 'node:crypto';

import * as argon2 from 'argon2';

import type { PrismaClient } from '../generated/prisma/client';
import { normalizeEmail } from './normalize-email';

export interface CreateAdminInput {
  email: string;
  name?: string;
  password?: string;
}

export interface CreateAdminOutput {
  user: {
    id: string;
    email: string;
    name: string | null;
    role: string;
  };
  password: string;
  isNewUser: boolean;
  passwordAutoGenerated: boolean;
}

export interface ParsedAdminCliArgs {
  email?: string;
  name?: string;
  password?: string;
  help?: boolean;
}

/**
 * Valida o formato de e-mail básico para garantir integridade.
 */
export function isValidEmail(email: string): boolean {
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  return emailRegex.test(email.trim());
}

/**
 * Gera uma senha aleatória de alta entropia contendo letras maiúsculas,
 * minúsculas, números e caracteres especiais seguros.
 */
export function generateSecurePassword(length = 16): string {
  const charset =
    'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz23456789!@#$%&*';
  const bytes = randomBytes(length);
  let password = '';
  for (let i = 0; i < length; i++) {
    const byte = bytes[i] ?? 0;
    password += charset[byte % charset.length];
  }
  return password;
}

/**
 * Interpreta argumentos passados via CLI (suporta flags curtas e longas com = ou espaço).
 * Ex: --email=admin@loja.com, --email admin@loja.com, -e admin@loja.com
 */
export function parseAdminCliArgs(args: string[]): ParsedAdminCliArgs {
  const parsed: ParsedAdminCliArgs = {};

  for (let i = 0; i < args.length; i++) {
    const arg = args[i] ?? '';

    if (arg === '--help' || arg === '-h') {
      parsed.help = true;
      return parsed;
    }

    if (arg.startsWith('--email=')) {
      parsed.email = arg.split('=', 2)[1];
    } else if (arg === '--email' || arg === '-e') {
      parsed.email = args[++i];
    } else if (arg.startsWith('--name=')) {
      parsed.name = arg.split('=', 2)[1];
    } else if (arg === '--name' || arg === '-n') {
      parsed.name = args[++i];
    } else if (arg.startsWith('--password=')) {
      parsed.password = arg.split('=', 2)[1];
    } else if (arg === '--password' || arg === '-p') {
      parsed.password = args[++i];
    }
  }

  return parsed;
}

/**
 * Texto de ajuda e documentação da CLI `admin:create`.
 */
export function getAdminCliHelp(): string {
  return [
    '===================================================================',
    ' PROVISIONAMENTO DE ADMINISTRADOR — COMMERCE-CORE',
    '===================================================================',
    '',
    'Uso:',
    '  pnpm run admin:create --email=<email> [--name=<nome>] [--password=<senha>]',
    '',
    'Parâmetros:',
    '  --email, -e     E-mail do administrador (obrigatório)',
    '  --name, -n      Nome completo do administrador (opcional, padrão: "Administrador")',
    '  --password, -p  Senha de acesso com no mínimo 8 caracteres (se omitida,',
    '                  uma senha segura de 16 caracteres será gerada automaticamente)',
    '  --help, -h      Exibe esta mensagem de ajuda',
    '',
    'Exemplos:',
    '  pnpm run admin:create --email="admin@minhaloja.com.br" --name="Maria Silva"',
    '  pnpm run admin:create --email="admin@minhaloja.com.br" --password="SenhaSegura123!"',
    '===================================================================',
  ].join('\n');
}

/**
 * Provisiona ou eleva um usuário ao papel de Administrador (`admin`),
 * configurando permissões completas, hash Argon2 e verificação imediata de e-mail.
 */
export async function provisionAdmin(
  input: CreateAdminInput,
  prisma: PrismaClient,
): Promise<CreateAdminOutput> {
  if (!input.email || !input.email.trim()) {
    throw new Error('O e-mail do administrador é obrigatório (--email).');
  }

  const normalizedEmail = normalizeEmail(input.email);
  if (!isValidEmail(normalizedEmail)) {
    throw new Error(
      `O endereço "${input.email}" não é um e-mail válido. Verifique o formato informado.`,
    );
  }

  let finalPassword = input.password?.trim();
  let passwordAutoGenerated = false;

  if (finalPassword) {
    if (finalPassword.length < 8) {
      throw new Error('A senha informada deve possuir no mínimo 8 caracteres.');
    }
  } else {
    finalPassword = generateSecurePassword(16);
    passwordAutoGenerated = true;
  }

  const passwordHash = await argon2.hash(finalPassword);

  // Garante a existência do papel de administrador
  let adminRole = await prisma.role.findUnique({
    where: { name: 'admin' },
  });

  if (!adminRole) {
    // Se o banco ainda não rodou seed, cria o papel admin com as permissões cadastradas
    const permissions = await prisma.permission.findMany({
      select: { id: true },
    });
    adminRole = await prisma.role.create({
      data: {
        name: 'admin',
        description: 'Full access to every permission in the catalog.',
        isDefault: false,
        permissions: {
          create: permissions.map((p) => ({ permissionId: p.id })),
        },
      },
    });
  }

  const existingUser = await prisma.user.findUnique({
    where: { email: normalizedEmail },
  });

  let userResult: { id: string; email: string; name: string | null };
  const isNewUser = !existingUser;

  if (existingUser) {
    userResult = await prisma.user.update({
      where: { id: existingUser.id },
      data: {
        roleId: adminRole.id,
        name: input.name?.trim() || existingUser.name,
        passwordHash,
        emailVerifiedAt: existingUser.emailVerifiedAt ?? new Date(),
      },
      select: { id: true, email: true, name: true },
    });
  } else {
    userResult = await prisma.user.create({
      data: {
        email: normalizedEmail,
        name: input.name?.trim() || 'Administrador',
        passwordHash,
        roleId: adminRole.id,
        emailVerifiedAt: new Date(),
      },
      select: { id: true, email: true, name: true },
    });
  }

  return {
    user: {
      id: userResult.id,
      email: userResult.email,
      name: userResult.name,
      role: 'admin',
    },
    password: finalPassword,
    isNewUser,
    passwordAutoGenerated,
  };
}

/**
 * Formata o resumo do provisionamento para exibição no terminal.
 */
export function formatAdminSummary(
  output: CreateAdminOutput,
  appUrl = 'http://localhost:5173',
): string {
  const actionText = output.isNewUser
    ? 'Novo Administrador Criado'
    : 'Usuário Existente Elevado a Administrador';

  const passwordText = output.passwordAutoGenerated
    ? `${output.password}  <-- [GERADA AUTOMATICAMENTE: copie e guarde em local seguro]`
    : '[Definida manualmente via parâmetro]';

  return [
    '===================================================================',
    ' PROVISIONAMENTO DE ADMINISTRADOR CONCLUÍDO COM SUCESSO',
    '===================================================================',
    ` Ação Realizada:   ${actionText}`,
    ` ID do Usuário:    ${output.user.id}`,
    ` Nome Completo:    ${output.user.name ?? 'Administrador'}`,
    ` E-mail:           ${output.user.email}`,
    ` Papel de Acesso:  ${output.user.role} (Acesso irrestrito a todas as operações)`,
    ` Status da Conta:  E-mail verificado (Pronto para login imediato)`,
    ` Senha de Acesso:  ${passwordText}`,
    ` Painel da Loja:   ${appUrl}/admin`,
    '===================================================================',
  ].join('\n');
}
